### ISSUE TITLE
Jamovi throws error in Windows

### ISSUE THREAD

**Issue by kylehamilton** [raviselker/medmod#1]
Not sure if I did something wrong but I get a DLL error when I sideloaded the module 

![image](https://user-images.githubusercontent.com/2274317/30353446-c60db4d0-97da-11e7-9e44-1888a5641389.png)

**Comment by kylehamilton** [comment]
Happens with both Mediation and Moderation

![image](https://user-images.githubusercontent.com/2274317/30353480-02f5d486-97db-11e7-87f5-6197676a48cf.png)

**Comment by jonathon-love** [comment]
if you're wondering what's going on here ravi, medmod depends on native code, which means it needs to be built for each OS separately.

**Comment by raviselker** [comment]
Hi Kyle, the `medmod` module is now available directly from the jamovi library. I removed the `.jmo` file from this repo because it only allowed you to sideload it on ubuntu zesty (which is a bit confusing). If you want to sideload `medmod` you need to build it on your own machine.
